export default {
  SEARCH_PODCASTS: 'SEARCH_PODCASTS',
  PODCASTS_RECEIVED: 'PODCASTS_RECEIVED',
  PODCAST_SELECTED: 'PODCAST_SELECTED',
  TRACKLIST_READY: 'TRACKLIST_READY',
  TRACKLIST_ERROR: 'TRACKLIST_ERROR',
  PODCASTS_RECEIVED_ERROR: 'PODCASTS_RECEIVED_ERROR'
};
